# Generated by Django 5.2.5 on 2025-08-19 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_master_options_alter_order_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="master",
            options={"verbose_name": "Мастер", "verbose_name_plural": "Мастера"},
        ),
        migrations.AlterField(
            model_name="order",
            name="appointment_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Назначенные дата и время"
            ),
        ),
    ]
