# Generated by Django 5.2.5 on 2025-08-17 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_decorimage_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="master",
            options={"verbose_name_plural": "Мастера"},
        ),
        migrations.AlterModelOptions(
            name="order",
            options={"verbose_name_plural": "Заказы"},
        ),
        migrations.AlterModelOptions(
            name="review",
            options={"verbose_name_plural": "Отзывы"},
        ),
        migrations.AlterModelOptions(
            name="service",
            options={"verbose_name_plural": "Услуги"},
        ),
    ]
