# Generated by Django 5.2.5 on 2025-08-15 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_decorimage_remove_master_address_remove_master_phone_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="decorimage",
            name="name",
            field=models.CharField(
                default="image_name",
                max_length=100,
                verbose_name="Читаемый идентификатор",
            ),
        ),
    ]
