# Generated by Django 5.2.5 on 2025-08-20 05:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_master_options_alter_order_appointment_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="appointment_date",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Назначенные дата и время",
            ),
            preserve_default=False,
        ),
    ]
