# Generated by Django 5.2.5 on 2025-08-14 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DecorImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="decor/",
                        verbose_name="Фотография",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="master",
            name="address",
        ),
        migrations.RemoveField(
            model_name="master",
            name="phone",
        ),
        migrations.RemoveField(
            model_name="master",
            name="services",
        ),
        migrations.AddField(
            model_name="master",
            name="bio",
            field=models.TextField(blank=True, verbose_name="О себе"),
        ),
        migrations.AddField(
            model_name="master",
            name="services_provided",
            field=models.ManyToManyField(to="core.service", verbose_name="Услуги"),
        ),
        migrations.AddField(
            model_name="review",
            name="services_were_provided",
            field=models.ManyToManyField(
                to="core.service", verbose_name="Оказанные услуги"
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="masters_who_provides",
            field=models.ManyToManyField(to="core.master", verbose_name="Мастера"),
        ),
        migrations.AlterField(
            model_name="master",
            name="photo",
            field=models.ImageField(
                blank=True, upload_to="master/", verbose_name="Фотография"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="appointment_date",
            field=models.DateTimeField(verbose_name="Назначенные дата и время"),
        ),
        migrations.AlterField(
            model_name="order",
            name="services",
            field=models.ManyToManyField(to="core.service", verbose_name="Услуги"),
        ),
        migrations.AlterField(
            model_name="service",
            name="image",
            field=models.ImageField(
                blank=True, upload_to="service/", verbose_name="Изображение"
            ),
        ),
    ]
